
CATEGORIES = ["Infrastructure", "IT & Network", "Sanitation", "Electrical", "General"]

PRIORITIES = ["low", "medium", "high", "urgent"]

TRAINING_DATA = [
    # Infrastructure
    ("Broken bench in classroom 204", "Infrastructure", "medium"),
    ("The classroom door lock is broken and does not close", "Infrastructure", "medium"),
    ("Large pothole near the main gate is dangerous for bikes", "Infrastructure", "high"),
    ("The library ceiling is leaking during rain", "Infrastructure", "high"),
    ("Crack in the wall of the hostel corridor", "Infrastructure", "high"),
    ("Broken window glass in the physics lab", "Infrastructure", "medium"),
    ("The staircase railing is loose and unsafe", "Infrastructure", "high"),
    ("Desk in the exam hall is damaged", "Infrastructure", "low"),
    ("Roof of the canteen is damaged and water comes inside", "Infrastructure", "high"),
    ("The footpath near the library is broken", "Infrastructure", "medium"),
    ("Classroom blackboard is cracked and hard to write on", "Infrastructure", "low"),
    ("The main gate is damaged and does not close properly", "Infrastructure", "medium"),
    ("Wall plaster is falling down in room 101", "Infrastructure", "high"),
    ("Hostel bunk bed is broken and shakes", "Infrastructure", "medium"),
    ("The sports ground fence is damaged", "Infrastructure", "low"),
    ("Projector screen mount is loose in the seminar hall", "Infrastructure", "low"),
    ("Broken floor tiles in the corridor cause slipping", "Infrastructure", "high"),
    ("Ceiling plaster has fallen down in room 12", "Infrastructure", "high"),
    ("The wooden door of the seminar hall is warped", "Infrastructure", "low"),
    ("Water seepage on the hostel wall during monsoon", "Infrastructure", "high"),
    ("The auditorium stage floor is damaged", "Infrastructure", "medium"),
    ("Door handle of classroom 108 has come off", "Infrastructure", "low"),
    ("The cycle stand near the gate is broken", "Infrastructure", "low"),
    ("Roof sheet of the workshop is torn", "Infrastructure", "high"),
    ("Hostel room window does not close and rain comes in", "Infrastructure", "medium"),
    ("The library table is shaky and damaged", "Infrastructure", "low"),
    ("Steps of the main building are broken", "Infrastructure", "high"),
    ("The notice board frame has fallen off the wall", "Infrastructure", "low"),

    # IT & Network
    ("Wi-Fi is not working in the hostel since yesterday", "IT & Network", "high"),
    ("No internet connection in the computer lab", "IT & Network", "high"),
    ("College website login page shows an error", "IT & Network", "medium"),
    ("Printer in the admin office is not working", "IT & Network", "low"),
    ("The projector in the smart classroom has no display", "IT & Network", "medium"),
    ("Wi-Fi signal is very weak in the library", "IT & Network", "medium"),
    ("Computer in lab 3 does not boot", "IT & Network", "medium"),
    ("Internet speed in the hostel is very slow at night", "IT & Network", "low"),
    ("Student portal password reset is not working", "IT & Network", "medium"),
    ("LAN port in the lab is not working", "IT & Network", "medium"),
    ("Projector remote is missing in room 210", "IT & Network", "low"),
    ("The online attendance system is down", "IT & Network", "high"),
    ("Email server is not delivering mails", "IT & Network", "high"),
    ("Wi-Fi keeps disconnecting in the canteen", "IT & Network", "medium"),
    ("Lab computer keyboard is not working", "IT & Network", "low"),
    ("Smart board is not responding to touch", "IT & Network", "medium"),
    ("Network switch in the server room is faulty", "IT & Network", "high"),
    ("CCTV camera in the corridor is offline", "IT & Network", "medium"),
    ("The attendance machine does not read ID cards", "IT & Network", "medium"),
    ("Internet is blocked on the library computers", "IT & Network", "medium"),
    ("Projector cable in room 105 is damaged", "IT & Network", "low"),
    ("Wi-Fi is not available in the new academic block", "IT & Network", "high"),
    ("Online exam portal is very slow", "IT & Network", "high"),
    ("The office desktop has become very slow", "IT & Network", "low"),
    ("Mouse and keyboard in lab 1 are not working", "IT & Network", "low"),
    ("Wi-Fi password is not being accepted after the update", "IT & Network", "low"),
    ("The college app crashes while opening results", "IT & Network", "medium"),
    ("Software is not installed on the lab computers", "IT & Network", "low"),

    # Sanitation
    ("Washroom is not cleaned since two days", "Sanitation", "high"),
    ("Dirty drinking water in the cooler", "Sanitation", "urgent"),
    ("Garbage bins are overflowing near the canteen", "Sanitation", "high"),
    ("Bad smell coming from the hostel washroom", "Sanitation", "high"),
    ("No water in the washroom taps", "Sanitation", "high"),
    ("Toilet flush is not working", "Sanitation", "medium"),
    ("Dustbin in the corridor is broken", "Sanitation", "low"),
    ("Classroom floor is not swept", "Sanitation", "medium"),
    ("Leaking tap near the canteen wastes water", "Sanitation", "medium"),
    ("Water cooler is not cleaned since long", "Sanitation", "medium"),
    ("Sweeping staff has not come to the second floor", "Sanitation", "medium"),
    ("Mosquito breeding in the stagnant water near the hostel", "Sanitation", "high"),
    ("Washroom door is broken in block B", "Sanitation", "medium"),
    ("Soap and handwash are not available in the washroom", "Sanitation", "low"),
    ("Drain near the canteen is blocked and overflowing", "Sanitation", "high"),
    ("Used plates are lying in the corridor", "Sanitation", "medium"),
    ("Water tank is not cleaned since many months", "Sanitation", "high"),
    ("Insects are coming out of the drain near the mess", "Sanitation", "high"),
    ("The washroom has no water since morning", "Sanitation", "high"),
    ("Garbage is not collected from the hostel since three days", "Sanitation", "high"),
    ("Foul smell from the drain outside the library", "Sanitation", "medium"),
    ("Broken mug and bucket are lying in the washroom", "Sanitation", "low"),
    ("Cockroaches are seen in the canteen kitchen", "Sanitation", "high"),
    ("The corridor is full of dust and needs cleaning", "Sanitation", "medium"),
    ("Drinking water has a strange taste and smell", "Sanitation", "urgent"),
    ("There is no dustbin near the main gate", "Sanitation", "low"),
    ("Sewage water is overflowing near the hostel gate", "Sanitation", "urgent"),
    ("Paper cups and wrappers are thrown in the classroom", "Sanitation", "low"),

    # Electrical
    ("Fan is not working in room 305", "Electrical", "medium"),
    ("Tube light is flickering in the corridor", "Electrical", "low"),
    ("Power cut in the hostel wing since morning", "Electrical", "high"),
    ("Burning smell from the lab socket", "Electrical", "urgent"),
    ("Light is not working in the staircase", "Electrical", "medium"),
    ("AC in the seminar hall is not cooling", "Electrical", "medium"),
    ("Switch board is sparking in lab 2", "Electrical", "urgent"),
    ("No power supply in the computer lab", "Electrical", "urgent"),
    ("Street light near the gate is off", "Electrical", "medium"),
    ("Bulb is fused in the library reading room", "Electrical", "low"),
    ("Loose wire hanging from the ceiling near the corridor", "Electrical", "urgent"),
    ("Generator did not start during the power cut", "Electrical", "high"),
    ("Exposed wire near the water cooler", "Electrical", "urgent"),
    ("Fan regulator is not working", "Electrical", "low"),
    ("Emergency light in the hostel is not working", "Electrical", "high"),
    ("Socket in the classroom is burnt", "Electrical", "high"),
    ("Fan makes a loud noise in room 22", "Electrical", "medium"),
    ("Switch in the library is not working", "Electrical", "medium"),
    ("Power fluctuation is damaging the lab computers", "Electrical", "urgent"),
    ("The main switch board is hot to touch", "Electrical", "urgent"),
    ("Tube light of the corridor has fallen down", "Electrical", "high"),
    ("No electricity in the seminar hall during the event", "Electrical", "high"),
    ("Fan speed is very slow even at full regulator", "Electrical", "low"),
    ("Wire is cut near the garden light", "Electrical", "high"),
    ("The lift stopped between floors with students inside", "Electrical", "urgent"),
    ("Inverter backup is not working in the hostel", "Electrical", "medium"),
    ("Charging point in the classroom is not working", "Electrical", "low"),
    ("The fuse keeps blowing in lab 5", "Electrical", "high"),

    # General
    ("Request for a new dustbin in the corridor", "General", "low"),
    ("Need more seating arrangement in the library", "General", "low"),
    ("The canteen menu is too costly for students", "General", "low"),
    ("Request to extend the library timings", "General", "low"),
    ("Lost my ID card and need a duplicate", "General", "low"),
    ("College bus is always late in the morning", "General", "medium"),
    ("Request for an extra notice board near the office", "General", "low"),
    ("Canteen food quality has become poor", "General", "medium"),
    ("Security guard is not present at the gate at night", "General", "high"),
    ("Ragging near the hostel block in the evening", "General", "urgent"),
    ("Request for a water dispenser on the third floor", "General", "low"),
    ("Car parking area is not marked properly", "General", "low"),
    ("Need a suggestion box near the office", "General", "low"),
    ("Sports equipment is not available for practice", "General", "low"),
    ("Fee receipt is not generated after payment", "General", "medium"),
    ("Stray dogs near the canteen are troubling students", "General", "medium"),
    ("Request for more cycles in the campus cycle stand", "General", "low"),
    ("Scholarship form is not available on the portal", "General", "medium"),
    ("Request to add more elective subjects", "General", "low"),
    ("A medical room should be provided in the campus", "General", "medium"),
    ("Transport fee receipt is not issued", "General", "low"),
    ("Request to allow late entry during exams", "General", "low"),
    ("Canteen is overcrowded during the lunch break", "General", "medium"),
    ("Request for a bigger reading room in the library", "General", "low"),
    ("Anti-ragging committee number is not displayed anywhere", "General", "medium"),
    ("Sports day was not organised this year", "General", "low"),
    ("Request for a bus stop near the hostel gate", "General", "low"),
    ("Canteen does not accept online payment", "General", "low"),
]
